[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/zmb3/spotify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "github.com/rydrman/go-itunes-library"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
